### PR TITLE
Add onDonationRequest dependency for ChariotConnect

### PR DESCRIPTION
**Pull request by themaxgoldman**
Before:
ChariotConnect would only load data from `onDonationRequest` function on initial page load. User would have to use `useRef` to create references to data so that data was always up to date for `ChariotConnect`

After:
ChariotConnect component has `onDonationRequest` as a dependency so listeners and elements are regenerated whenever underlying data updates.

### CODE REVIEW

**Review by Neilshweky — APPROVED** [review]
Love it!

**Comment by Neilshweky** [comment]
Can you explain to me why this works? The onDonationRequest function itself doesn't change, just the params. Does this still update?

**Comment by themaxgoldman** [comment]
> Can you explain to me why this works? The onDonationRequest function itself doesn't change, just the params. Does this still update?
will take this offline

**Comment by Neilshweky** [comment]
Also have we considered if this could be a breaking change for some users of the library?

**Comment by magaldima** [comment]
> > Can you explain to me why this works? The onDonationRequest function itself doesn't change, just the params. Does this still update?
> 
> will take this offline

@themaxgoldman lets try and keep questions and answers like this on GitHub so that we have a public record of these things.

**Comment by themaxgoldman** [comment]
> Also have we considered if this could be a breaking change for some users of the library?

Hey so my understanding of react is still very limited but from what I understand the function is called once when page spins up. When you add that dependency the page is rerendered every time the dependencies on that function change which means the function will be called again.

From ChatGPT: 
```
The problem here is that the useEffect hook has an empty dependency array, [], which means that it runs only once when the component mounts. Because of this, the onDonationRequest callback set during this initialization will capture the environment (closure) from the first render and won't be updated in subsequent renders.

This causes stale data to be used in the onDonationRequest function when you're relying on state values that change over time.
```

**Comment by salo1serfati** [comment]
Nice! Was this tested? 

Once you made the change, how were you able to test it in your local repo? 

Also, once this is complete, @themaxgoldman you should try using our React SDK on our app.givechariot.com/demo page to see if the SDK is working properly!

**Comment by themaxgoldman** [comment]
> Nice! Was this tested?
> 
> Once you made the change, how were you able to test it in your local repo?
> 
> Also, once this is complete, @themaxgoldman you should try using our React SDK on our app.givechariot.com/demo page to see if the SDK is working properly!

Yeah it was tested by duplicating the react repo locally and pulling it into a playground locally.
Will do!

**Pull request merged**
